<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Études statistiques | La tarification a priori</title>
  <meta name="description" content="Projet de tarification a priori" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Études statistiques | La tarification a priori" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://bookdown.org/abdouloudoussdiakite/Tarification/logo.png" />
  <meta property="og:description" content="Projet de tarification a priori" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Études statistiques | La tarification a priori" />
  
  <meta name="twitter:description" content="Projet de tarification a priori" />
  <meta name="twitter:image" content="https://bookdown.org/abdouloudoussdiakite/Tarification/logo.png" />

<meta name="author" content="Abdoul Oudouss DIAKITE, Othmane ETTADLAOUI" />


<meta name="date" content="2022-06-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="les-modèles-linéaires-généralisés.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">La tarification a priori</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#objectif"><i class="fa fa-check"></i><b>0.1</b> Objectif</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#les-données-du-projets"><i class="fa fa-check"></i><b>0.2</b> Les données du projets</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#description-des-données"><i class="fa fa-check"></i><b>0.3</b> Description des données</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="etudestats.html"><a href="etudestats.html"><i class="fa fa-check"></i><b>1</b> Études statistiques</a>
<ul>
<li class="chapter" data-level="1.1" data-path="etudestats.html"><a href="etudestats.html#nettoyage-des-données"><i class="fa fa-check"></i><b>1.1</b> Nettoyage des données</a></li>
<li class="chapter" data-level="1.2" data-path="etudestats.html"><a href="etudestats.html#représentations-graphiques"><i class="fa fa-check"></i><b>1.2</b> Représentations graphiques</a></li>
<li class="chapter" data-level="1.3" data-path="etudestats.html"><a href="etudestats.html#tests-statistiques"><i class="fa fa-check"></i><b>1.3</b> Tests statistiques</a>
<ul>
<li class="chapter" data-level="" data-path="etudestats.html"><a href="etudestats.html#estimation-par-la-méthode-du-maximum-de-vraisembance."><i class="fa fa-check"></i>Estimation par la méthode du maximum de vraisembance.</a></li>
<li class="chapter" data-level="" data-path="etudestats.html"><a href="etudestats.html#nombre-de-sinistres"><i class="fa fa-check"></i>Nombre de sinistres</a></li>
<li class="chapter" data-level="" data-path="etudestats.html"><a href="etudestats.html#charges-de-sinistres"><i class="fa fa-check"></i>Charges de sinistres</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="les-modèles-linéaires-généralisés.html"><a href="les-modèles-linéaires-généralisés.html"><i class="fa fa-check"></i><b>2</b> Les modèles linéaires généralisés</a>
<ul>
<li class="chapter" data-level="" data-path="les-modèles-linéaires-généralisés.html"><a href="les-modèles-linéaires-généralisés.html#régression-logistique-ou-probit"><i class="fa fa-check"></i>Régression logistique ou probit</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modèle-collectif.html"><a href="modèle-collectif.html"><i class="fa fa-check"></i><b>3</b> Modèle collectif</a></li>
<li class="chapter" data-level="" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i>Conclusion</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">La tarification a priori</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="etudestats" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">1</span> Études statistiques<a href="etudestats.html#etudestats" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="nettoyage-des-données" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Nettoyage des données<a href="etudestats.html#nettoyage-des-données" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cette partie de ce document sera consacrée à l’étude statistique de notre jeu de données.<br />
Il existe quelques incohérences au niveau des données telles que des charges négatives ou nulles pour des nombres de sinistres positifs et des nombres de sinistres nuls pour des charges positives.
Nous avons donc choisi de remplacer par 0 toutes les charges négatives pour des sinistres nuls, tous les nombres de sinistres positifs pour des charges nulles et par la valeur absolue des charges pour les nombre de sinistres positifs.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="etudestats.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="etudestats.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajout de la somme des sinistres par police</span></span>
<span id="cb2-3"><a href="etudestats.html#cb2-3" aria-hidden="true" tabindex="-1"></a>database<span class="sc">$</span>SumSINAPS <span class="ot">&lt;-</span> database <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;SINAP&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="etudestats.html#cb2-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">apply</span>(., <span class="dv">1</span>, sum)</span>
<span id="cb2-5"><a href="etudestats.html#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformation des données</span></span>
<span id="cb2-6"><a href="etudestats.html#cb2-6" aria-hidden="true" tabindex="-1"></a>database <span class="ot">&lt;-</span>  database <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">SumSINAPS =</span> <span class="fu">case_when</span>(CHARGE<span class="sc">==</span><span class="dv">0</span><span class="sc">~</span><span class="dv">0</span>,</span>
<span id="cb2-7"><a href="etudestats.html#cb2-7" aria-hidden="true" tabindex="-1"></a>                                            <span class="cn">TRUE</span><span class="sc">~</span>SumSINAPS)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-8"><a href="etudestats.html#cb2-8" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">mutate</span>(<span class="at">CHARGE =</span> <span class="fu">case_when</span>(SumSINAPS<span class="sc">==</span><span class="dv">0</span><span class="sc">~</span><span class="dv">0</span>,</span>
<span id="cb2-9"><a href="etudestats.html#cb2-9" aria-hidden="true" tabindex="-1"></a>                                                 SumSINAPS<span class="sc">&gt;</span><span class="dv">0</span><span class="sc">~</span><span class="fu">abs</span>(CHARGE),</span>
<span id="cb2-10"><a href="etudestats.html#cb2-10" aria-hidden="true" tabindex="-1"></a>                                                 <span class="cn">TRUE</span><span class="sc">~</span><span class="dv">0</span>))</span></code></pre></div>
<p>Nous venons de créer avec le code précédent une nouvelle colonne dans la base de données <code>database</code> que nous avons appelé <code>SumSINAPS</code>.
On peut facilement faire un sommaire de la somme des sinistres ainsi que des charges avec la fonction <code>summary</code> afin de connaître les mesures de tendance de cette variable.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="etudestats.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(database[,<span class="fu">c</span>(<span class="st">&quot;CHARGE&quot;</span>,<span class="st">&quot;SumSINAPS&quot;</span>)])</span></code></pre></div>
<pre><code>##      CHARGE          SumSINAPS     
##  Min.   :    0.0   Min.   : 0.000  
##  1st Qu.:    0.0   1st Qu.: 0.000  
##  Median :    0.0   Median : 0.000  
##  Mean   :  170.1   Mean   : 0.169  
##  3rd Qu.:    0.0   3rd Qu.: 0.000  
##  Max.   :95151.0   Max.   :10.000</code></pre>
</div>
<div id="représentations-graphiques" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Représentations graphiques<a href="etudestats.html#représentations-graphiques" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dans cette partie du projet, nous allons effectuer un ensemble de représentations graphiques afin de savoir l’impact des variables sur les sinistres.<br />
Ces graphes suivants indiquent la fréquence des sinistre en fonction des différentes variables : sexe, zone, catégorie socio-professionnelle, age, usage du véhicule et statut matrimonial.<br />
</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="etudestats.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-2"><a href="etudestats.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-3"><a href="etudestats.html#cb5-3" aria-hidden="true" tabindex="-1"></a>B1 <span class="ot">=</span> database <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="at">SEXE =</span> SEX,STATUT,ZONE,CSP,USAGE,AGECOND) <span class="co">#selection des variables.</span></span>
<span id="cb5-4"><a href="etudestats.html#cb5-4" aria-hidden="true" tabindex="-1"></a>plot_ <span class="ot">&lt;-</span> <span class="cf">function</span>(df, N){</span>
<span id="cb5-5"><a href="etudestats.html#cb5-5" aria-hidden="true" tabindex="-1"></a>  name <span class="ot">=</span> <span class="fu">names</span>(df)</span>
<span id="cb5-6"><a href="etudestats.html#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> name){</span>
<span id="cb5-7"><a href="etudestats.html#cb5-7" aria-hidden="true" tabindex="-1"></a>    df0 <span class="ot">&lt;-</span>  <span class="fu">data.frame</span>(df[[i]],N) <span class="co"># Creation d&#39;une df(Variables,N)</span></span>
<span id="cb5-8"><a href="etudestats.html#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colnames</span>(df0) <span class="ot">&lt;-</span> <span class="fu">c</span>(i,<span class="st">&#39;N&#39;</span>)</span>
<span id="cb5-9"><a href="etudestats.html#cb5-9" aria-hidden="true" tabindex="-1"></a>    s <span class="ot">&lt;-</span> df0 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="at">valeur =</span> df0[[i]]) <span class="sc">%&gt;%</span> </span>
<span id="cb5-10"><a href="etudestats.html#cb5-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(N)) <span class="co"># Creation d&#39;une df(groupe de Variables, Total)</span></span>
<span id="cb5-11"><a href="etudestats.html#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">assign</span>(<span class="fu">paste0</span>(<span class="st">&quot;table&quot;</span>,i),s,.GlobalEnv)</span>
<span id="cb5-12"><a href="etudestats.html#cb5-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-13"><a href="etudestats.html#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># debut du code pour la figure</span></span>
<span id="cb5-14"><a href="etudestats.html#cb5-14" aria-hidden="true" tabindex="-1"></a>    figure <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> s, <span class="fu">aes</span>(<span class="at">x =</span> valeur, <span class="at">y =</span> total<span class="sc">/</span><span class="fu">sum</span>(total))) <span class="sc">+</span></span>
<span id="cb5-15"><a href="etudestats.html#cb5-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb5-16"><a href="etudestats.html#cb5-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">xlab</span>(i) <span class="sc">+</span>  <span class="co"># Ajout du label de x</span></span>
<span id="cb5-17"><a href="etudestats.html#cb5-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ylab</span>(<span class="fu">paste0</span>(<span class="st">&quot;Frequence &quot;</span>,i)) <span class="sc">+</span> <span class="co"># Ajout du label de y</span></span>
<span id="cb5-18"><a href="etudestats.html#cb5-18" aria-hidden="true" tabindex="-1"></a>      hrbrthemes<span class="sc">::</span><span class="fu">theme_ipsum</span>(<span class="at">grid =</span> <span class="st">&quot;Y&quot;</span>) <span class="co"># Ajout d&#39;un theme pour la figure</span></span>
<span id="cb5-19"><a href="etudestats.html#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># fin du code pour la figure</span></span>
<span id="cb5-20"><a href="etudestats.html#cb5-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-21"><a href="etudestats.html#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">assign</span>(<span class="fu">paste0</span>(<span class="st">&quot;fig&quot;</span>,i),figure,.GlobalEnv) <span class="co">#assigantion de la figure i </span></span>
<span id="cb5-22"><a href="etudestats.html#cb5-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb5-23"><a href="etudestats.html#cb5-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-24"><a href="etudestats.html#cb5-24" aria-hidden="true" tabindex="-1"></a>SumSINAPS<span class="ot">=</span>database<span class="sc">$</span>SumSINAPS</span>
<span id="cb5-25"><a href="etudestats.html#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_</span>(B1,SumSINAPS) <span class="co"># Execution de la fonction precedente</span></span></code></pre></div>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="etudestats.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(patchwork)</span>
<span id="cb6-2"><a href="etudestats.html#cb6-2" aria-hidden="true" tabindex="-1"></a>(figSEXE<span class="sc">|</span>figUSAGE)<span class="sc">/</span>figAGECOND</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="etudestats.html#cb7-1" aria-hidden="true" tabindex="-1"></a>(figSTATUT<span class="sc">|</span>figZONE)<span class="sc">/</span>figCSP</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>On constate que pour la variable <code>SEX</code> la fréquence des sinistres des hommes(M) est plus que le double de celle des femmes(F).<br />
Les clients du type d’usage de véhicule <span class="math inline">\(2\)</span> ont les fréquences les plus élevées de sinistres, suivit dans cet ordre par les usages <span class="math inline">\(1\)</span>,<span class="math inline">\(3\)</span> et <span class="math inline">\(4\)</span>.<br />
Les conducteurs de statut <em>A</em> ont une fréquence de sinistre à peu près cinq fois plus élevées que celle des conducteurs de statut <em>C</em>.<br />
On peut utiliser ce même raisonnement pour interpréter tous les autres graphes.</p>
</div>
<div id="tests-statistiques" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Tests statistiques<a href="etudestats.html#tests-statistiques" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Nous allons faire des tests statistiques histoire de connaître quelle loi suit la somme totale des sinistres <code>SumSINAPS</code>.
Les tests d’adéquation servent à tester si un échantillon est distribué selon une loi de probabilité donnée.
Ils permettent de décider, avec un seuil d’erreur <span class="math inline">\(\alpha\)</span> spécifié, si les écarts présentés par l’échantillon par rapport aux valeurs théoriques attendues sont dus au hasard ou sont au contraire significatifs.</p>
<div id="estimation-par-la-méthode-du-maximum-de-vraisembance." class="section level3 unnumbered hasAnchor">
<h3>Estimation par la méthode du maximum de vraisembance.<a href="etudestats.html#estimation-par-la-méthode-du-maximum-de-vraisembance." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Soit <span class="math inline">\(X\)</span> une variable aléatoire réelle de loi discrète ou continue dont on veut estimer le paramétre <span class="math inline">\(\theta\)</span>. Alors on définit une fonction <span class="math inline">\(f\)</span> telle que:<br />
<span class="math display">\[f(x;\theta) = \begin{cases}
    f_\theta(x) : si\; X\;variable\; aléatoire\; continue \\
    P_\theta(X=x) : si\; X\;variable\; aléatoire\; discrète
\end{cases}\]</span></p>
<p>On appelle fonction de vraisemblance de <span class="math inline">\(\theta\)</span> pour une réalisation <span class="math inline">\((x_1,\dots,x_n)\)</span> d’un échantillon, la fonction de <span class="math inline">\(\theta\)</span>:<br />
<span class="math display">\[L(x_1,\dots,x_n;\theta)=f(x_1,\dots,x_n;\theta)=\prod\limits_{i=1}^{n}f(x;\theta)\]</span></p>
<p>La méthode consiste à estimer <span class="math inline">\(\theta\)</span> par la valeur qui maximise <span class="math inline">\(L\)</span>, cette méthode s’appelle méthode du maximum de vraisemblance(<span class="math inline">\(MLE\)</span><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>), on choisit la valeur <span class="math inline">\(\theta\)</span> qui réalise le maximum de <span class="math inline">\(L(x_1,\dots,x_n;\theta)\)</span>. Pour cela on cherche <span class="math inline">\(\theta\)</span> telle que:<br />
<span class="math display">\[\frac{\partial L}{\partial \theta}=0 \;\; et\;\; \frac{\partial^2 L}{\partial \theta^2}\leq 0\]</span></p>
<p>On passe en général au logarithme, c’est à dire on cherche <span class="math inline">\(\theta\)</span> telle que:<br />
<span class="math display">\[\frac{\partial\big(ln(L)\big)}{\partial \theta}=0 \;\; et\;\; \frac{\partial^2 \big(ln(L)\big)}{\partial \theta^2}\leq 0\]</span></p>
</div>
<div id="nombre-de-sinistres" class="section level3 unnumbered hasAnchor">
<h3>Nombre de sinistres<a href="etudestats.html#nombre-de-sinistres" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour faire les tests, nous allons générer une variable aléatoire <span class="math inline">\(X\)</span> suivant une loi choisie, puis tester si la somme totale des sinistres <code>SumSINAPS</code> est de même loi.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div id="loi-de-poisson" class="section level4 unnumbered hasAnchor">
<h4>Loi de poisson<a href="etudestats.html#loi-de-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dans le cas habituel théorique, le nombre de sinistres suivrait la loi de poisson ce qui nous pousse à faire ce premier test.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="etudestats.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Generer une v.a de longueur indentique a celle de SumSINAPS et suivant la loi de poisson</span></span>
<span id="cb8-2"><a href="etudestats.html#cb8-2" aria-hidden="true" tabindex="-1"></a>X<span class="ot">=</span><span class="fu">rpois</span>(<span class="fu">length</span>(SumSINAPS),<span class="fu">mean</span>(SumSINAPS))</span>
<span id="cb8-3"><a href="etudestats.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#test de poisson</span></span>
<span id="cb8-4"><a href="etudestats.html#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(SumSINAPS,X)</span></code></pre></div>
<pre><code>## 
##  Two-sample Kolmogorov-Smirnov test
## 
## data:  SumSINAPS and X
## D = 0.076048, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<p>La <span class="math inline">\(p\)</span>-<span class="math inline">\(value\)</span> est inférieure à <span class="math inline">\(0.5\)</span> donc on rejette l’hypothèse <span class="math inline">\(H_0\)</span> selon laquelle la somme des sinistres suit une loi de poisson.
Pour consolider cette conclusion on peut faire un test visuel avec la fonction <code>qqplot()</code>.
Si <code>SumSINAPS</code> et <span class="math inline">\(X\)</span> suivent la même loi, alors le nuage de points doit s’apparenter à une droite.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="etudestats.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqplot</span>(SumSINAPS,X)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>On voit clairement que le nuage de points est loin d’être sur une même droite, ce qui conforte notre conclusion précédente.</p>
</div>
<div id="loi-géométrique" class="section level4 unnumbered hasAnchor">
<h4>Loi géométrique<a href="etudestats.html#loi-géométrique" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A part la loi de poisson, le nombre de sinistre pourrait suivre la loi géométrique.
D’ailleur la densité de <code>SumSINAPS</code> que nous avons tracer a la même forme que le graphe d’une densité de la loi géométrique.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>On peut tester graphiquement si une variable suit une loi géométrique toujours avec la même fonction <code>qqplot()</code>.
Mais faudra trouver le paramètre <span class="math inline">\(p\)</span> de la loi loi géométrique pour pouvoir générer notre échantillon <span class="math inline">\(X\)</span>.
Il existe un package permettant d’entraîner une donnée selon la loi loi géométrique du nom de fitdistrplus<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> afin de trouver l’estimateur du paramètre <span class="math inline">\(p\)</span> par la méthode du maximum de vraisemblance.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="etudestats.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fitdistrplus)</span>
<span id="cb11-2"><a href="etudestats.html#cb11-2" aria-hidden="true" tabindex="-1"></a>fitSINAPS <span class="ot">&lt;-</span> <span class="fu">fitdist</span>(<span class="at">data =</span> SumSINAPS,<span class="at">distr =</span> <span class="st">&quot;geom&quot;</span>,</span>
<span id="cb11-3"><a href="etudestats.html#cb11-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">&quot;mle&quot;</span>)</span>
<span id="cb11-4"><a href="etudestats.html#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitSINAPS)</span></code></pre></div>
<pre><code>## Fitting of the distribution &#39; geom &#39; by maximum likelihood 
## Parameters : 
##       estimate  Std. Error
## prob 0.8554255 0.002564721
## Loglikelihood:  -7767.809   AIC:  15537.62   BIC:  15545.3</code></pre>
<p>La sortie de la fonction <code>summary</code> indique que <span class="math inline">\(p =0.8554255\)</span>, on va l’utiliser pour générer <span class="math inline">\(X\)</span> puis faire le test de <code>qqplot</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="etudestats.html#cb13-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">rgeom</span>(<span class="fu">length</span>(SumSINAPS),<span class="at">prob =</span><span class="fl">0.8554255</span>)</span>
<span id="cb13-2"><a href="etudestats.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqplot</span>(SumSINAPS,X)</span>
<span id="cb13-3"><a href="etudestats.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Ce graphe s’apparente plus avec une droite que celui tracer dans la section précédente.
En plus le modèle entraîné présente des valeurs empériques et théoriques très proche.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="etudestats.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fitSINAPS)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<blockquote>
<p>On peut donc supposé que <span class="math inline">\(SumSINAPS\sim\mathcal{G}(p:= 0.8554255)\)</span></p>
</blockquote>
</div>
</div>
<div id="charges-de-sinistres" class="section level3 unnumbered hasAnchor">
<h3>Charges de sinistres<a href="etudestats.html#charges-de-sinistres" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Comme nous l’avons fait précédemment, nous allons chercher le meilleur paramétré <span class="math inline">\(\mu log\)</span> et <span class="math inline">\(sdlog\)</span> par la méthode <span class="math inline">\(MLE\)</span> pour la charge des sinistres qui suivrait une loi lognormale.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="etudestats.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fitdistrplus)</span>
<span id="cb15-2"><a href="etudestats.html#cb15-2" aria-hidden="true" tabindex="-1"></a>Charge <span class="ot">&lt;-</span> database<span class="sc">$</span>CHARGE</span>
<span id="cb15-3"><a href="etudestats.html#cb15-3" aria-hidden="true" tabindex="-1"></a>Charge <span class="ot">&lt;-</span> Charge[<span class="fu">which</span>(Charge<span class="sc">&gt;</span><span class="dv">0</span>)]</span>
<span id="cb15-4"><a href="etudestats.html#cb15-4" aria-hidden="true" tabindex="-1"></a>fitCharge <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(Charge,<span class="st">&quot;log-normal&quot;</span>)</span>
<span id="cb15-5"><a href="etudestats.html#cb15-5" aria-hidden="true" tabindex="-1"></a>fitCharge</span></code></pre></div>
<pre><code>##     meanlog       sdlog   
##   6.66608145   1.38553971 
##  (0.03901768) (0.02758967)</code></pre>
<p>Autrement dit, si la charge de sinistres suit une loi lognormale alors ce sera:<br />
<span class="math display">\[log\mathcal{N}(6.66608145,1.38553971)\]</span> On peut faire le test de Kolmogorov-Smirnov<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> pour conforter se résultat en tenant compte de l’écart type des erreurs d’estimation de la fonction <code>fitdistr</code>.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="etudestats.html#cb17-1" aria-hidden="true" tabindex="-1"></a>estimated <span class="ot">=</span> fitCharge<span class="sc">$</span>estimate <span class="sc">+</span> fitCharge<span class="sc">$</span>sd</span>
<span id="cb17-2"><a href="etudestats.html#cb17-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(<span class="fu">length</span>(Charge),estimated[[<span class="st">&quot;meanlog&quot;</span>]],estimated[[<span class="st">&quot;sdlog&quot;</span>]])</span>
<span id="cb17-3"><a href="etudestats.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(Charge,X)</span></code></pre></div>
<pre><code>## 
##  Two-sample Kolmogorov-Smirnov test
## 
## data:  Charge and X
## D = 0.048374, p-value = 0.1046
## alternative hypothesis: two-sided</code></pre>
<p>La <span class="math inline">\(p-value = 0.1046&gt;\alpha=5\%\)</span> alors on rejette pas l’hypothèse <span class="math inline">\(H_0\)</span>, alors la charge de sinistres pourrait suivre la loi <span class="math inline">\(log\mathcal{N}(6.7,1.4)\)</span>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="etudestats.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-2"><a href="etudestats.html#cb19-2" aria-hidden="true" tabindex="-1"></a>dfdensity <span class="ot">=</span> <span class="fu">data.frame</span>(Charge,X)</span>
<span id="cb19-3"><a href="etudestats.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dfdensity)<span class="sc">+</span></span>
<span id="cb19-4"><a href="etudestats.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>Charge,<span class="at">color =</span><span class="st">&quot;blue&quot;</span>))<span class="sc">+</span></span>
<span id="cb19-5"><a href="etudestats.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">color=</span><span class="st">&quot;red&quot;</span>))<span class="sc">+</span></span>
<span id="cb19-6"><a href="etudestats.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>( <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>),</span>
<span id="cb19-7"><a href="etudestats.html#cb19-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">labels=</span> <span class="fu">c</span>(<span class="st">&quot;Charge&quot;</span>,<span class="st">&quot;X&quot;</span>))<span class="sc">+</span></span>
<span id="cb19-8"><a href="etudestats.html#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Densités&quot;</span>,</span>
<span id="cb19-9"><a href="etudestats.html#cb19-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle =</span> <span class="st">&quot;X a été généré aléatoirement</span><span class="sc">\n</span><span class="st">Suivant la loi loi lognormale&quot;</span>)<span class="sc">+</span></span>
<span id="cb19-10"><a href="etudestats.html#cb19-10" aria-hidden="true" tabindex="-1"></a>  ggthemes<span class="sc">::</span><span class="fu">theme_tufte</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-19"></span>
<img src="_main_files/figure-html/unnamed-chunk-19-1.png" alt="On peut constater que les densité de X et Charge sont presque les mêmes" width="480" />
<p class="caption">
Figure 1.1: On peut constater que les densité de X et Charge sont presque les mêmes
</p>
</div>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>MLE : <em>Maximum likelihood estimation</em><a href="etudestats.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p><a href="https://cran.r-project.org/web/packages/fitdistrplus/index.html" class="uri">https://cran.r-project.org/web/packages/fitdistrplus/index.html</a><a href="etudestats.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p><a href="https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test" class="uri">https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test</a><a href="etudestats.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="les-modèles-linéaires-généralisés.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/AODiakite/Tarification/edit/master/01-stats.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
